# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5412ed6edc8f667cda78f97535c7c37fa5f0e0d9fadab08c0e468dc85c81d537643d8be1b3353ae260d84bb5103bf321495ba5aaf3d291edbb7af990f81e416

test:
  secret_key_base: d2ea99089c9a7313853156b94cde684c810d0d3a7031013567e300138a5a3fd54b14c5ff207fca992309fda13066b521bfcaf409f50abcfb95f8e69257348732

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
